In [1]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist
(X_train,y_train),(X_test,y_test) = mnist.load_data()
X_train,X_test = X_train/255, X_test/255

In [5]:
model = tf.keras.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                            tf.keras.layers.Dense(128,activation='relu'),
                            tf.keras.layers.Dropout(0.2),
                            tf.keras.layers.Dense(10)])

C:\Users\HP\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [8]:
predictions = model(X_train[:1]).numpy()
predictions

array([[-0.30343115, -0.21203938, -0.33488622,  0.07086309, -0.91111887,
        -0.37204662,  0.0514509 , -0.08236586, -0.19865197, -0.5137072 ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.09441769, 0.10345329, 0.091494  , 0.13728   , 0.0514207 ,
        0.08815644, 0.1346408 , 0.11777707, 0.10484758, 0.07651236]],
      dtype=float32)

In [10]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1],predictions).numpy()

2.4286423

In [12]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.8570 - loss: 0.4857
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9555 - loss: 0.1497
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9672 - loss: 0.1111
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9737 - loss: 0.0861
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9768 - loss: 0.0754


In [13]:
model.evaluate(X_test,y_test,verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9797 - loss: 0.0716


[0.0715552270412445, 0.9797000288963318]

In [14]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(X_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[1.6334505e-08, 9.5016830e-09, 1.3209959e-04, 3.5947631e-04,
        2.1665306e-12, 4.0709025e-08, 7.5810492e-14, 9.9950516e-01,
        8.9177774e-07, 2.3160553e-06],
       [3.5973713e-10, 1.0245012e-04, 9.9988925e-01, 7.3995825e-06,
        3.1707652e-14, 4.0070904e-07, 2.8223090e-08, 3.1222643e-13,
        4.5843663e-07, 2.4492712e-14],
       [2.8441967e-08, 9.9961144e-01, 2.4013882e-05, 1.2817600e-06,
        5.2645679e-05, 6.2359331e-06, 1.3661013e-05, 2.1814017e-04,
        7.2235889e-05, 4.5423900e-07]], dtype=float32)>